name: chip8
version: 0.0.2
description: >-
  A Chip-8 emulator in Dart
author: Matt Sullivan <matt.j.sullivan@gmail.com>
homepage: https://github.com/mjohnsullivan/chip8

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.6.0
  
dev_dependencies:
  test: ^1.14.5